name: societymanagement
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.9.0
  cloud_firestore: ^0.14.1+3
  connectivity: ^0.4.9+3
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  flutter_offline: ^0.3.0
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^7.1.1
  intl: ^0.16.1
  razorpay_flutter: ^1.2.2
  shared_preferences: ^0.5.12
  url_launcher: ^5.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Allura
      fonts:
      - asset: assets/Allura-Regular.ttf
    - family: Bitter
      fonts:
      - asset: assets/Bitter-Italic-VariableFont_wght.ttf
    - family: SourceSansPro
      fonts:
      - asset: assets/SourceSansPro-Regular.ttf
    - family: Roboto
      fonts:
      - asset: assets/Roboto-Regular.ttf